import { assert } from "@samual/assert"
import * as diff from "diff"
import { isEmpty, omitBy } from "es-toolkit/compat"
import MagicString from "magic-string"
import path from "node:path"
import prettier from "prettier"
import type { SourceMapInput } from "rolldown"
import type { Options } from "."

/**
 * The plugin options that are currently supported.
 */
const OPTIONS = new Set([
  'sourcemap',
  'cwd',
]);

/**
 * Resolve prettier config, using `resolveConfig` by default, switch to `resolveConfigSync` otherwise.
 * If none of these methods are available, returns `null` as a fallback.
 *
 * @param cwd The current working directory.
 * @returns A promise resolved with prettier configuration, or null.
 */
function resolvePrettierConfig(cwd: string): Promise<object | null> {
  // Since prettier 3.1.1, the resolver searches from a file path, not a directory.
  // Let's fake it by concatenating with a file name.
  const fromFile = path.join(cwd, '__noop__.js');

  if (prettier.resolveConfig) {
    return prettier.resolveConfig(fromFile);
  }

  return Promise.resolve(null);
}

/**
 * The plugin.
 *
 * @class
 */
export class RollupPluginPrettier {
  declare name: string
  _options: Promise<Partial<Options> | undefined>
  _sourcemap
  /**
   * Initialize plugin & prettier.
   *
   * @param options Initalization option.
   */
  constructor(options: Options = {}) {
    // Initialize main options.
    this._options = Promise.resolve(
      omitBy((options), (_value, key) => OPTIONS.has(key)),
    );

    // Try to resolve config file if it exists
    const cwd = "cwd" in options ? options.cwd : process.cwd();
    this._options = Promise.all([resolvePrettierConfig(cwd), this._options]).then((results) => (
      Object.assign({}, ...results.map((result) => result || {}))
    ));

    // Reset empty options.
    this._options = this._options.then((opts) => (
      isEmpty(opts) ? undefined : opts
    ));

    // Check if sourcemap is enabled by default.
    this._sourcemap = "sourcemap" in options ? options.sourcemap : null;
  }

  /**
   * Get the `sourcemap` value.
   *
   * @return The `sourcemap` flag value.
   */
  getSourcemap() {
    return this._sourcemap;
  }

  /**
   * Disable sourcemap.
   */
  enableSourcemap() {
    this._sourcemap = true;
  }

  /**
   * Reformat source code using prettier.
   *
   * @param source The source code to reformat.
   * @param outputOptions Output options.
   * @return The transformation result.
   */
  async reformat(source: string, outputOptions?: { sourcemap: boolean }): Promise<{ code: string, map?: SourceMapInput }> {
    return this._reformat(source, outputOptions, await this._options)
  }

  /**
   * Reformat source code using prettier.
   *
   * @param source The source code to reformat.
   * @param outputOptions Output options.
   * @param options Prettier options.
   * @returns The reformat response.
   * @private
   */
  async _reformat(source: string, outputOptions?: { sourcemap: boolean }, options?: object): Promise<{ code: string, map?: SourceMapInput }> {
    return this._processOutput(source, outputOptions?.sourcemap, await prettier.format(source, options))
  }

  /**
   * Process output generated by prettier:
   * - Generate sourcemap if need be.
   * - Otherwise returns prettier output as chunk output.
   *
   * @param source The source code to reformat.
   * @param sourcemap If sourcemap should be generated or not.
   * @param output Prettier output.
   * @returns The reformat response.
   * @private
   */
  _processOutput(source: string, sourcemap: boolean | undefined | null, output: string): { code: string, map?: SourceMapInput } {
    // Should we generate sourcemap?
    // The sourcemap option may be a boolean or any truthy value (such as a `string`).
    // Note that this option should be false by default as it may take a (very) long time.
    const defaultSourcemap = this._sourcemap == null ? false : this._sourcemap;
    const outputSourcemap = sourcemap == null ? defaultSourcemap : sourcemap;
    if (!outputSourcemap) {
      return { code: output };
    }

    if (defaultSourcemap !== 'silent') {
      console.warn(`[${this.name}] Sourcemap is enabled, computing diff is required`);
      console.warn(`[${this.name}] This may take a moment (depends on the size of your bundle)`);
    }

    const magicString = new MagicString(source);
    const changes = diff.diffChars(source, output);

    if (changes && changes.length > 0) {
      let idx = 0;

      changes.forEach((part) => {
        if (part.added) {
          magicString.prependLeft(idx, part.value);
          idx -= part.count;
        } else if (part.removed) {
          magicString.remove(idx, idx + part.count);
        }

        idx += part.count;
      });
    }

    return {
      code: magicString.toString(),
      map: magicString.generateMap({
        hires: true,
      }),
    };
  }
}

assert(Reflect.defineProperty(RollupPluginPrettier.prototype, `name`, { value: `rolldown-plugin-prettier` }))
